### PR TITLE
[WIP] Add: Avena sdrd service

### PR DESCRIPTION
**Pull request by facastiblancor**
This PR adds sdrd, a docker-container with the Ettus Research UHD and GNURadio libraries to support running GNURadio-generated scripts inside a container.

TO DO:

- [ ] Test service with USB USRPs (B200mini)
- [ ] Test with network-based USRPs (N210, X310, USRP1&2, etc.)
- [ ] Write a NATS code for Avena-compliant status checking.

### CODE REVIEW

**Comment by abalmos** [comment]
Is the goal of this container to be used as a base layer for other containers?.

**Comment by facastiblancor** [comment]
Kind of. For the moment, this is more a wrapper of both UHD and GNURadio able to run scripts exported from block diagrams. It could be made into a base container for future services that require access to SDRs, but would need to rethink a bit the way it works.

**Comment by abalmos** [comment]
How do you add the scripts?

**Comment by facastiblancor** [comment]
Will close this PR, as most of the work has been superseeded by the Avena FM service

**Pull request closed without merging**
