### PR TITLE
Change Prometheus prefix to be j1939 

### PR DESCRIPTION
**Pull request by facastiblancor**
This PR changes the Prometheus prefix to be 'j1939', instead of being customizable by the NATS_SUB environment variable. This is due to Prometheus being not compatible with NATS subject semantics, especially with the topic separation characters (aka dots)

### CODE REVIEW

**Review by abalmos — APPROVED** [review]
Unfortunate.

**Comment by abalmos** [comment]
We should probably just use `cross` rather than all this custom vendoring. I had promised to fix this build chain, but never got to it.

Is this blocking you?

**Comment by facastiblancor** [comment]
Wanted to try `cross` but couldn't see how to integrate it to our GH actions workflow. It is not blocking me right now. Just wanted to try adding cross-compilation to see if I could reduce build times for rust services. I might add a couple of services in the future and wanted to avoid the slow emulator-based build. If this does not work, I will revert to the original QEMU builder and merge the code that needed attention.

**Comment by abalmos** [comment]
This is clo

**Comment by facastiblancor** [comment]
Added a **very crude** cross-compiling routine for the j1939d service in the dockerfile. So far it works, but a proper GHA cross-compiling flow for Rust containers must be considered in the future.

**Comment by facastiblancor** [comment]
Services now build correctly without errors, and the fix is working on our test stand units.

**Pull request merged**
