### PR TITLE
Kept gps_nats. changed ip to localhost

### PR DESCRIPTION
**Pull request by ksoontho**
Brought back gps_nats. 
Change ip to localhost

### CODE REVIEW

**Comment by ksoontho** [comment]
> You might want to change _natspy_ to _nats-py_ in the requirements.txt file. Also, please delete the `docker-compose-example.yml` and `docker-compose-text.yml.unfinished` files. They are not necessary.

I created a new commit. LMK if you can see it.

**Comment by abalmos** [comment]
@ksoontho I think you forgot to add your changes to requirements.txt. I think that is all that is left and I can run the CI which will build the image

**Comment by ksoontho** [comment]
Fixed.

**Comment by abalmos** [comment]
It's building now. The CI is a bit dodgy and rebuilds everything. Some of the services take a while. I'll try to keep an eye on it and let you know the results.

**Comment by abalmos** [comment]
Oh, shoot. We forgot something. I need you to edit this file: 

https://github.com/oats-center/isoblue/blob/9975ec7396986064436bc331ad2d4632ef3130b5/.github/workflows/build-and-push-services.yml#L21

And add your new folder to that list

**Comment by abalmos** [comment]
Here is your service build:

https://github.com/oats-center/isoblue/runs/6032852592?check_suite_focus=true

**Comment by abalmos** [comment]
Yikes. This is annoying. 

Apparently the tag name in docker hub has to lower case and we automatically use the exact service name to create the tag...

I suggest change the folder name from `CapstonePython` to something like `j1939_filter` and then update the workflows file.

**Comment by abalmos** [comment]
https://github.com/oats-center/isoblue/runs/6032943573?check_suite_focus=true

**Comment by ksoontho** [comment]
wow. by clicking that link am i watching it in real time?

**Comment by abalmos** [comment]
Good job guys. Merging and it should be up on docker hub in a few minutes.

**Comment by abalmos** [comment]
https://github.com/oats-center/isoblue/runs/6032982786?check_suite_focus=true

**Comment by abalmos** [comment]
Here it is on dockerhub:

https://hub.docker.com/r/isoblue/j1939_filter

@facastiblancor what's next?

**Comment by facastiblancor** [comment]
Only needs testing. Will deploy on dev05 and then later this week to the Skid-steer when available.

**Pull request merged**
