### PR TITLE
WIP - Addition of LattePanda Enclosure STEP files

### PR DESCRIPTION
**Pull request by ericpokeefe**
Initial commit of all LattePanda enclosure files. Designs were generated using Autodesk Fusion 360 and exported as .STEP files. The enclosure includes 4 SMA connectors, 1 USB connector, 1 RJ45 connector, 1 Isobus connector, and 8 LEDs. The mounting plate will fit either a LattePanda Alpha or Delta and will be machined from 6061 aluminum.

### CODE REVIEW

**Comment by ericpokeefe** [comment]
Work in Progress - Not ready to merge with Master
- Need to confirm all dimensions and tolerances for use with BIDC tools
- Need to create technical drawings and add images of the enclosure and mounting plate

**Comment by aaron97neu** [comment]
@ericpokeefe I forgot to mention this when we talked but my convention we name our branches either `feature/xxx` or `bugfix/yyy` so I should have instructed you to name your branch `feature/lattepandaenclosurev1`. Not a big deal and it is fine for this PR but we should fix it in the future

**Comment by ericpokeefe** [comment]
Sounds good Aaron, I will make sure to use that naming convention in the future.

**Review by abalmos — APPROVED** [review]
Haven't reviewed, but given this is new work with no certain expectations yet, I think we can just merge.

**Comment by abalmos** [comment]
Thanks @ericpokeefe for getting this up here. What is the status on machining?

**Comment by ericpokeefe** [comment]
@abalmos I am planning to stop in MSEE tomorrow to pick up the dead LattePanda board to confirm dimensions. We should be ready to machine at BIDC shortly after that. Also, I am going to commit a few technical drawings before merging.

**Pull request merged**
